{
 "title": "evol metrics",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "Reproduction expectancy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "carnivorousReproductionExpectancyGod",
     "legendFormat": "carnivorous"
    },
    {
     "expr": "herbivorousReproductionExpectancyGod",
     "legendFormat": "herbivorous"
    }
   ]
  },
  {
   "title": "Reward on death",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(rewardOnDeathHerbivorous[5m])",
     "legendFormat": "Herbivorous"
    },
    {
     "expr": "avg_over_time(rewardOnDeathCarnivorous[5m])",
     "legendFormat": "Carnivorous"
    }
   ]
  },
  {
   "title": "Reward on eat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(rewardOnEatHerbivorous[5m])",
     "legendFormat": "Herbivorous"
    },
    {
     "expr": "avg_over_time(rewardOnEatCarnivorous[5m])",
     "legendFormat": "Carnivorous"
    }
   ]
  },
  {
   "title": "Reward on reproduce",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(rewardOnReproduceHerbivorous[5m])",
     "legendFormat": "Herbivorous"
    },
    {
     "expr": "avg_over_time(rewardOnReproduceCarnivorous[5m])",
     "legendFormat": "Carnivorous"
    }
   ]
  },
  {
   "title": "Agents in use",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Amount of agents" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(herbivorousInUse[5m])",
     "legendFormat": "Herbivorous"
    },
    {
     "expr": "avg_over_time(carnivorousInUse[5m])",
     "legendFormat": "Carnivorous"
    }
   ]
  },
  {
   "title": "Reward on act",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(rewardOnActHerbivorous[5m])",
     "legendFormat": "Herbivorous"
    },
    {
     "expr": "avg_over_time(rewardOnActCarnivorous[5m])",
     "legendFormat": "Carnivorous"
    }
   ]
  },
  {
   "title": "Eat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(eatCarnivorous[5m])", "legendFormat": "Carnivorous" },
    { "expr": "rate(eatHerbivorous[5m])", "legendFormat": "Herbivorous" }
   ]
  },
  {
   "title": "Species life expectancy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(herbivorousSpecieLifeExpectancy[5m])",
     "legendFormat": "Herbivorous"
    },
    {
     "expr": "avg_over_time(carnivorousSpecieLifeExpectancy[5m])",
     "legendFormat": "Carnivorous"
    }
   ]
  },
  {
   "title": "Reproduction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(reproductionHerbivorous[5m])",
     "legendFormat": "Herbivorous"
    },
    {
     "expr": "rate(reproductionCarnivorous[5m])",
     "legendFormat": "Carnivorous"
    }
   ]
  },
  {
   "title": "Life expectancy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Amount of actions before death" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(actionsHerbivorous[10m])",
     "legendFormat": "Herbivorous"
    },
    {
     "expr": "avg_over_time(actionsCarnivorous[10m])",
     "legendFormat": "Carnivorous"
    }
   ]
  },
  {
   "title": "Cumulative reward",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(cumulativeRewardHerbivorous[10m])",
     "legendFormat": "Herbivorous"
    },
    {
     "expr": "avg_over_time(cumulativeRewardCarnivorous[10m])",
     "legendFormat": "Carnivorous"
    },
    {
     "expr": "avg_over_time(cumulativeRewardGod[5m])",
     "legendFormat": "God"
    }
   ]
  },
  {
   "title": "Reset count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(reset[5m])" }
   ]
  },
  {
   "title": "Life gain",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(lifeGainHerbivorous[5m])",
     "legendFormat": "Herbivorous"
    },
    {
     "expr": "avg_over_time(lifeGainCarnivorous[5m])",
     "legendFormat": "Carnivorous"
    }
   ]
  },
  {
   "title": "Life loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(lifeLossHerbivorous[10m])",
     "legendFormat": "Herbivorous"
    },
    {
     "expr": "avg_over_time(lifeLossCarnivorous[10m])",
     "legendFormat": "Carnivorous"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(speedHerbivorous[5m])",
     "legendFormat": "Herbivorous"
    },
    {
     "expr": "avg_over_time(speedCarnivorous[5m])",
     "legendFormat": "Carnivorous"
    }
   ]
  }
 ]
}